### ISSUE TITLE
No module named request

### ISSUE THREAD

**Issue by ghost** [Viralmaniar/Passhunt#7] opened 2018-03-06 17:45 UTC
On Kali, pip3 isn't installed by default. The person would need to first do an "apt-get install python3-pip". Additionally, there would be an error saying the following:

Traceback (most recent call last):
  File "passhunt.py", line 11, in <module>
    import urllib.request
ImportError: No module named request

The person would need to run "python3 passhunt.py"

**Comment by BaderSZ** [comment] 2018-03-06 17:54
This is a duplicate of issue #4 , a pull request is already available and should be merged to fix this.

**Closed as completed** 2018-03-09 02:27 UTC
